# Generated by Django 5.2.5 on 2026-04-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_category_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
