# Generated by Django 5.2.5 on 2026-05-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
    ]
